package uk.ac.horizon.apptest.desktop
 
import uk.ac.horizon.apptest.model.ContentMapping;
import uk.ac.horizon.apptest.model.UserRegion;
import uk.ac.horizon.apptest.model.UserContentNotification;

rule "Enter region content"
    dialect "mvel"
	when
		ur : UserRegion ( )
		cm : ContentMapping ( region_id == ur.region_id )
	then
	System.out.println( "User "+ur.user_id+" given content "+cm.content_id+" via region "+ur.region_id ); 
	
//	create ( new UserContentNotification ( user_id = ur.user_id, content_id = cm.content_id ) );
end
