#created on: 22-Jun-2010
# Hyperplace-proxy facts

package uk.ac.horizon.ug.hyperplace.facts

// hyperplace main client type
declare HyperplaceClient
	@client // client type
	id : String @key 
end

// tab to show
declare HyperplaceTab
	@message // kind of sent to HyperplaceClients
	standard : boolean // for all clients
	clientId : String @to("HyperplaceClient") // may be null for standard
	name : String
	type : String // probably a fixed set of options?! (HPActionTab, HPARTab, HPDebugTab, HPWebTab, HPMapTab)
	stateGroup : String // defaults Action AR Map
	rank : float // to sort
	icon : String @type("URL")
end

// asset to cache
declare HyperplaceAsset 
	@message // kind of sent to HyperplaceClients
	standard : boolean // for all clients
	clientId : String @to("HyperplaceClient") // may be null for standard
	url : String @type("URL")
end

// action for user
declare HyperplaceAction
	@message // kind of sent to HyperplaceClients
	standard : boolean // for all clients
	clientId : String @to("HyperplaceClient") // may be null for standard
	title : String
	actionName : String // would be Class name in hyperplace
	// ...
end

// message to user
declare HyperplaceMessage
	@message // kind of sent to HyperplaceClients
	standard : boolean // for all clients
	clientId : String @to("HyperplaceClient") // may be null for standard
	message : String
	vibrate : int // duration
	dialog : boolean // dialog (rather than toast) message (may not be supported in Hyperplace client)
	dialogTitle : String // dialog title (may not be supported in Hyperplace client)
	dialogButtonText : String // (may not be supported in Hyperplace client)
	dialogIcon : String // (may not be supported in Hyperplace client)
end


// action by user
declare HyperplaceActionPerformed
	@message
	time : long
	clientId : String @msgfrom("HyperplaceClient") // can't use 'from' as it is a DRL keyword
	actionName : String // would be Class name in hyperplace
	jsonData : String // should be more structured?!
	// ...	
end
