package uk.ac.horizon.exserver.test1

import uk.ac.horizon.ug.commonfacts.SystemTime

import java.util.Date

declare User
	@Client
	@Input
	@Single
	@Required
	name : String
	id : String @ClientId @key
	location : String @Dimension("location")
	date : Date
	bval : boolean
	ival : int
	dval : double
end

declare Output
	@Client
	@Output
	@Multiple
	@Optional
	user_id : String @ClientId
	message : String
end

rule "test rule 1"
	dialect "mvel"
	when 
		u : User ( )
	then
 		Output o = new Output();
		o.user_id = u.id;
		o.message = "Hello "+u.name;
		insert( o );
end

rule "test output"
	dialect "mvel"
	when
		o : Output ( $m : message )
	then
		System.out.println("Output: "+$m);
end

rule "tick" 
	dialect "mvel"
	when 
		$st : SystemTime ( $t : time )
	then 
		System.out.println("Time is now "+$t);
end

rule "agenda group test"
	dialect "mvel"
	agenda-group "test"
	when
		s : SystemTime()
	then 
		System.out.println("Agenda group test fired!");		
end
