package uk.ac.horizon.exserver.test1

import uk.ac.horizon.ug.commonfacts.SystemTime

import java.util.Date

declare User
	name : String
	id : String
	location : String
	date : Date
	bval : boolean
	ival : int
	dval : double
end

declare Output
	user_id : String
	message : String
end

rule "test rule 1"
	when 
		u : User ()
	then
		Output o = new Output();
		o.setUser_id( u.getId() );
		o.setMessage( "Hello "+u.getName() );
		insert( o );
end
