package uk.ac.horizon.exserver.test1

import uk.ac.horizon.ug.commonfacts.SystemTime

import java.util.Date

declare User
	@Client
	@Input
	@Single
	@Required
	name : String
	id : String @ClientId
	location : String @Dimension("location")
	date : Date
	bval : boolean
	ival : int
	dval : double
end

declare Output
	@Client
	@Output
	@Multiple
	@Optional
	user_id : String @ClientId
	message : String
end

rule "test rule 1"
	dialect "mvel"
	when 
		u : User ( )
	then
 		Output o = new Output();
		o.user_id = u.id;
		o.message = "Hello "+u.name;
		insert( o );
end
